lint-and-test:
  image: python:3.9
  stage: test
  before_script:
    - echo "nothing"
  script:
    - echo "nothing"
  only:
    - staging-1.3
    - ci


trigger_assembly:
  stage: .post
  trigger:
    project: cdci/dispatcher/cdci_docker_dispatcher
    branch: staging-1.3

  only:
    - staging-1.3
    - ci
